name: CD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        password: ${{ env.secrets.PASSWORD }}
        username: ${{ env.secrets.USERNAME }}
        host: ${{ env.secrets.HOST }}
        script: |
          whoami
          ls -al
