name: CD
on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    needs: CI
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        password: ${{ secrets.PASSWORD }}
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        script: |
          cd review-app
          bash deploy.sh
