name: CD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      private_key: ${{ secrets.PRIVATE_KEY }}
      username: ${{ secrets.USERNAME }}
      host: ${{ secrets.HOST }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        key: ${{ env.private_key }}
        username: ${{ env.username }}
        host: ${{ env.host }}
        script: |
          whoami
          ls -al
